[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "emcee_rapper"
version = "0.0.1"

dependencies = [
  "numpy",
  "corner",
  "matplotlib",
  "emcee"
]
